let xAxisData=[
    {
        "name":'Jan',
        "sale":112_000
    },
    {
        "name":'Feb',
        "sale":99_000
    },
    {
        "name":'Mar',
        "sale":12_000
    },
    {
        "name":'Apr',
        "sale":110_000
    },
    {
        "name":'May',
        "sale":54_000
    },
    {
        "name":'Jun',
        "sale":85_000
    },
    {
        "name":'Jul',
        "sale":34_000
    },
    {
        "name":'Agu',
        "sale":18_000
    },
    {
        "name":'Sep',
        "sale":0
    },    {
        "name":'Oct',
        "sale":73_000
    },    {
        "name":'Nov',
        "sale":12_900
    },
    {
        "name":'Dec',
        "sale":15_000
    },
]
export {xAxisData}